// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewJsonFile() {
  return window['go']['main']['App']['CreateNewJsonFile']();
}

export function GetSavedConfig() {
  return window['go']['main']['App']['GetSavedConfig']();
}

export function OpenJsonFile() {
  return window['go']['main']['App']['OpenJsonFile']();
}

export function WriteStringToFile(arg1, arg2) {
  return window['go']['main']['App']['WriteStringToFile'](arg1, arg2);
}
