// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewJsonFile():Promise<any>;

export function GetSavedConfig():Promise<string>;

export function OpenJsonFile():Promise<any>;

export function WriteStringToFile(arg1:string,arg2:string):Promise<void>;
